// generated by generate_problems_js.py
const problems = {
  2: { correct: ['opt4'] },
  3: { correct: ['opt2'] },
  4: { correct: ['opt2'] },
  5: { correct: ['opt1'] },
  6: { correct: ['opt3', 'opt4'] },
  7: { correct: ['opt4'] },
  8: { correct: ['opt2'] },
  9: { correct: ['opt4'] },
  10: { correct: ['opt5'] },
  11: { correct: ['opt1', 'opt3'] },
  12: { correct: ['opt3'] },
  13: { correct: ['opt1', 'opt3'] },
  14: { correct: ['opt2'] },
  15: { correct: ['opt2'] },
  16: { correct: ['opt2'] },
  17: { correct: ['opt3'] },
  18: { correct: ['opt2'] },
  19: { correct: ['opt4'] },
  20: { correct: ['opt2'] },
  21: { correct: ['opt4'] },
  22: { correct: ['opt1'] },
  23: { correct: ['opt1'] },
  24: { correct: ['opt3'] },
  25: { correct: ['opt2'] },
  26: { correct: ['opt2'] },
  27: { correct: ['opt4'] },
  28: { correct: ['opt2', 'opt5'] },
  29: { correct: ['opt1', 'opt5'] },
  30: { correct: ['opt4'] },
  31: { correct: ['opt4'] },
  32: { correct: ['opt3'] },
  33: { correct: ['opt4', 'opt6'] },
  34: { correct: ['opt2'] },
  35: { correct: ['opt1'] },
  36: { correct: ['opt4'] },
  37: { correct: ['opt2'] },
  38: { correct: ['opt3'] },
  39: { correct: ['opt3'] },
  40: { correct: ['opt4'] },
  41: { correct: ['opt2'] },
  42: { correct: ['opt2'] },
  43: { correct: ['opt4'] },
  44: { correct: ['opt5'] },
  45: { correct: ['opt3'] },
  46: { correct: ['opt3'] },
  47: { correct: ['opt3'] },
  48: { correct: ['opt4'] },
  49: { correct: ['opt2', 'opt3'] },
  50: { correct: ['opt1'] },
  51: { correct: ['opt1'] },
  52: { correct: ['opt2'] },
  53: { correct: ['opt4'] },
  54: { correct: ['opt2'] },
  55: { correct: ['opt3'] },
  56: { correct: ['opt3', 'opt4'] },
  57: { correct: ['opt2', 'opt5'] },
  58: { correct: ['opt3'] },
};

/* 問題番号を表示する関数 */
function setProblemNumber() {
  const problemNumber = document.getElementById("problemNumber").getAttribute("value");
  document.getElementById("problemNumber").textContent = problemNumber;
}

window.onload = function () {
  setProblemNumber();
};

/* 正解判定と表示 */
function oK() {
  const problemNumber = Number(document.getElementById("problemNumber").getAttribute("value"));
  const problem = problems[problemNumber];
  const selected = Array.from(document.querySelectorAll('input[name="checkbox"]:checked, input[name="radio"]:checked')).map(item => item.value);

  if (selected.length === 0) {
    alert("答えを選択してね！");
    return;
  }

  if (problem.correct.length === selected.length && problem.correct.every(value => selected.includes(value))) {
    const mark = document.getElementById("correctMark");
    mark.classList.remove("show");
    setTimeout(function () {
      mark.classList.add("show");
    }, 10);
    setTimeout(function () {
      mark.classList.remove("show");
    }, 30000);
    return;
  }

  if (problem.correct.some(value => selected.includes(value))) {
    alert("一個あってる！もう一個選びなおしてね！");
  } else {
    alert("2つとも選びなおしてね！");
  }
}

/* 答えボタン押下時 */
function showAnswer() {
  const result = confirm("答え見てみる？");
  if (result) {
    document.getElementById("modal1").style.display = "block";
    openModal("OK");
  } else {
    alert("ファイト！");
    closeModal();
  }
}

/* モーダルを開く */
function openModal(num) {
  if (num === "OK") {
    const problemNumber = document.getElementById("problemNumber");
    answerText(problemNumber);
  }
}

/* モーダルを閉じる */
function closeModal() {
  document.getElementById("modal1").style.display = "none";
}
