/* generated by generate_problems_js.py */
const pageNames = [
  null,
  "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty", "twentyone", "twentytwo", "twentythree", "twentyfour", "twentyfive", "twentysix", "twentyseven", "twentyeight", "twentynine", "thirty", "thirtyone", "thirtytwo", "thirtythree", "thirtyfour", "thirtyfive", "thirtysix", "thirtyseven", "thirtyeight", "thirtynine", "forty", "fortyone", "fortytwo", "fortythree", "fortyfour", "fortyfive", "fortysix", "fortyseven", "fortyeight", "fortynine", "fifty", "fiftyone", "fiftytwo", "fiftythree", "fiftyfour", "fiftyfive", "fiftysix", "fiftyseven", "fiftyeight", "p59", "p60", "p61", "p62", "p63", "p64", "p65", "p66", "p67", "p68", "p69", "p70"
];

window.customPageNames = (pageNames[0] === null) ? pageNames.slice(1) : pageNames;
window.customTotalPages = window.customPageNames.length;
window.pageBasePath = "";

function setProblemNumber() {
  const problemNumber = document.getElementById("problemNumber").getAttribute("value");
  document.getElementById("problemNumber").textContent = problemNumber;
}

window.onload = function () {
  setProblemNumber();
};

function goNext(btn) {
  const problemNumber = Number(document.getElementById("problemNumber").getAttribute("value"));
  const nextNumber = Math.min(problemNumber + 1, window.customTotalPages);
  location.href = window.pageBasePath + window.customPageNames[nextNumber - 1] + ".html";
}

function goBack(btn) {
  const problemNumber = Number(document.getElementById("problemNumber").getAttribute("value"));
  if (problemNumber === 1) {
    location.href = "../index.html";
    return;
  }
  const prevNumber = Math.max(problemNumber - 1, 1);
  location.href = window.pageBasePath + window.customPageNames[prevNumber - 1] + ".html";
}
