// generated by generate_problems_js.py
const problems = {
  1: { correct: ['opt3'] },
  2: { correct: ['opt3'] },
  3: { correct: ['opt1'] },
  4: { correct: ['opt1'] },
  5: { correct: ['opt4', 'opt5'] },
  6: { correct: ['opt2', 'opt4'] },
  7: { correct: ['opt4'] },
  8: { correct: ['opt4'] },
};

/* 問題番号を表示する関数 */
function setProblemNumber() {
  const problemNumber = document.getElementById("problemNumber").getAttribute("value");
  document.getElementById("problemNumber").textContent = problemNumber;
}

window.onload = function () {
  setProblemNumber();
};

/* 正解判定と表示 */
function oK() {
  const problemNumber = Number(document.getElementById("problemNumber").getAttribute("value"));
  const problem = problems[problemNumber];
  const selected = Array.from(document.querySelectorAll('input[name="checkbox"]:checked, input[name="radio"]:checked')).map(item => item.value);

  if (selected.length === 0) {
    alert("答えを選択してね！");
    return;
  }

  if (problem.correct.length === selected.length && problem.correct.every(value => selected.includes(value))) {
    const mark = document.getElementById("correctMark");
    mark.classList.remove("show");
    setTimeout(function () {
      mark.classList.add("show");
    }, 10);
    setTimeout(function () {
      mark.classList.remove("show");
    }, 30000);
    return;
  }

  if (problem.correct.some(value => selected.includes(value))) {
    alert("一個あってる！もう一個選びなおしてね！");
  } else {
    alert("2つとも選びなおしてね！");
  }
}

/* 答えボタン押下時 */
function showAnswer() {
  const result = confirm("答え見てみる？");
  if (result) {
    document.getElementById("modal1").style.display = "block";
    openModal("OK");
  } else {
    alert("ファイト！");
    closeModal();
  }
}

/* モーダルを開く */
function openModal(num) {
  if (num === "OK") {
    const problemNumber = document.getElementById("problemNumber");
    answerText(problemNumber);
  }
}

/* モーダルを閉じる */
function closeModal() {
  document.getElementById("modal1").style.display = "none";
}
