/* generated by generate_problems_js.py */
const pageNames = [
  null,
  "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen"
];

window.customPageNames = (pageNames[0] === null) ? pageNames.slice(1) : pageNames;
window.customTotalPages = window.customPageNames.length;
window.pageBasePath = "";

function setProblemNumber() {
  const problemNumber = document.getElementById("problemNumber").getAttribute("value");
  document.getElementById("problemNumber").textContent = problemNumber;
}

window.onload = function () {
  setProblemNumber();
};

function goNext(btn) {
  const problemNumber = Number(document.getElementById("problemNumber").getAttribute("value"));
  const nextNumber = Math.min(problemNumber + 1, window.customTotalPages);
  location.href = window.pageBasePath + window.customPageNames[nextNumber - 1] + ".html";
}

function goBack(btn) {
  const problemNumber = Number(document.getElementById("problemNumber").getAttribute("value"));
  if (problemNumber === 1) {
    location.href = "../index.html";
    return;
  }
  const prevNumber = Math.max(problemNumber - 1, 1);
  location.href = window.pageBasePath + window.customPageNames[prevNumber - 1] + ".html";
}
